#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S2,     colorSensor,    sensorI2CCustom)
#pragma config(Sensor, S3,     sonarSensor,    sensorSONAR)
#pragma config(Sensor, S4,     eopdSensor,     sensorAnalogActive)
#pragma config(Motor,  mtr_S1_C1_1,     turretMotor,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     armMotor,      tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    wristServoPitch,      tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    wristServoYaw,        tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    clawServoRight,       tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    clawServoLeft,        tServoStandard)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "C:\Program Files (x86)\Robomatter Inc\ROBOTC Development Environment\Sample Programs\NXT\3rd Party Sensor Drivers\drivers\lego-ultrasound.h"
#include "C:\Program Files (x86)\Robomatter Inc\ROBOTC Development Environment\Sample Programs\NXT\3rd Party Sensor Drivers\drivers\hitechnic-colour-v2.h"
#include "C:\Program Files (x86)\Robomatter Inc\ROBOTC Development Environment\Sample Programs\NXT\3rd Party Sensor Drivers\drivers\hitechnic-eopd.h"


#include "JoystickDriver.c"

//--------------------------------------
//					Global Variables
//--------------------------------------

int sonarDistanceReading;
float eopdReading = 0;
int red;
int green;
int blue;


//--------------------------------------
//					Control methods
//--------------------------------------

void armTurretRight(int inputSpeed)
{
	motor[turretMotor] = inputSpeed;
}

void armTurretLeft(int inputSpeed)
{
	motor[turretMotor] = -inputSpeed;
}

void armMotorRight(int inputSpeed)
{
	motor[armMotor] = inputSpeed;
}

void armMotorLeft(int inputSpeed)
{
	motor[armMotor] = -inputSpeed;
}

int grabObject()
{
	servo[clawServoRight] = 140;
	servo[clawServoLeft] = 0;

	return 0;
}

int releaseObject()
{
	servo[clawServoRight] = 0;
	servo[clawServoLeft] = 140;

	return 140;
}

//--------------------------------------
//					Autonomous hand methods
//--------------------------------------

bool searchForBlocks()
{
	if (red > 90 && green > 45 && eopdReading <= 1.3 && eopdReading >= 1.1) {
		return true;
	}
	else {
		return false;
	}
}

//--------------------------------------
//								Tasks
//--------------------------------------

task updateJoystickSettings()
{
  while (true)
    getJoystickSettings(joystick);
}

task updateSensors()
{
    static bool EOPDlongRange;

    if (!HTCS2readRGB(colorSensor, red, green, blue))
    {
        nxtDisplayTextLine(4, "ERROR!!");
        wait1Msec(2000);
        StopAllTasks();
    }

//    HTEOPDsetShortRange(eopdSensor);
    HTEOPDsetLongRange(eopdSensor);
    EOPDlongRange = true;

    while (true)
    {
        HTCS2readRGB(colorSensor, red, green, blue);
        sonarDistanceReading = SensorValue[sonarSensor];
        if (EOPDlongRange == true) {
            eopdReading = 412.5/HTEOPDreadRaw(eopdSensor);
        }
        else {
            eopdReading = 112.5/HTEOPDreadRaw(eopdSensor);
        }
    }
}

void checkButtons()
{
		writeDebugStreamLine("s\te\tr\tg\tb");
		writeDebugStreamLine("%i\t%f\t%i\t%i\t%i", sonarDistanceReading, eopdReading, red, green, blue);
		wait1Msec(50);
		clearDebugStream();

    if (joy1Btn(1))
    {

    }
    else if (joy1Btn(2))
    {

    }
    else if (joy1Btn(3))
    {

    }
    else if (joy1Btn(4))
    {

    }
    else if (joy1Btn(5))
    {

    }
    else if (joy1Btn(6))
    {

    }
    else if (joy1Btn(7))
    {

  	}
  	else if (joy1Btn(8))
    {

  	}
  	else if (joy1Btn(9))
    {

  	}
  	else if (joy1Btn(10))
    {

  	}
    else
    {

    }
}


task main()
{
	clearDebugStream();

	StartTask(updateJoystickSettings);
	StartTask(updateSensors);

	//writeDebugStreamLine("Long Range");
	//writeDebugStreamLine("proc\traw");

	releaseObject();
	while (true)
	{
		//writeDebugStreamLine("%i\t%i\t", eopdReading, HTEOPDreadRaw(eopdSensor));
		//wait1Msec(5);

		if (searchForBlocks() == true) {
			grabObject();
			writeDebugStreamLine("Block Found!");
		}
		else {
			releaseObject();
		}

		checkButtons();

		if (joystick.joy1_TopHat != -1)
		{
      if (joystick.joy1_TopHat == 0)
      {
				armMotorRight(25);
				motor[turretMotor] = 0;
      }
      if (joystick.joy1_TopHat == 4)
      {
      	armMotorLeft(25);
      	motor[turretMotor] = 0;
      }
      if (joystick.joy1_TopHat == 2)
      {
				armTurretRight(15);
				motor[armMotor] = 0;
      }
      if (joystick.joy1_TopHat == 6)
      {
				armTurretLeft(15);
				motor[armMotor] = 0;
      }
    }
    else if ( abs(joystick.joy1_x2) > 20)
    {
      if (joystick.joy1_x2 > 20)
      {

      }
      else if (joystick.joy1_x2 < -20)
      {

      }
    }
    else if ( abs(joystick.joy1_y1) > 20)
    {
      if (joystick.joy1_x2 > 20)
      {

      }
      else if (joystick.joy1_x2 < -20)
      {

      }
    }
    else
    {
			 motor[turretMotor] = 0;
			 motor[armMotor] = 0;
    }
	}
}
