#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     testMotor,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

/*
	Essentials for encoder:
		float getEncoderRotationsFloat(float encoderCounts)
		{ return (float)(encoderCounts/1424); }

		int getEncoderRotationsInt(float encoderCounts)
		{ return (int)(encoderCounts/1424); }

		nMotorEncoder[testMotor];
*/

long encVal;
float motorRotations = 0;

void move(float joystickSettings)
{
	motor[testMotor] = (int)(joystickSettings * 0.7874);
}

float getEncoderRotationsFloat(float encoderCounts)
{ return (float)(encoderCounts/1424); }

int getEncoderRotationsInt(float encoderCounts)
{ return (int)(encoderCounts/1424); }

task main()
{

	nMotorEncoder[testMotor] = 0; //Any value you put here resets the encoder to zero

	while(true)
	{
		getJoystickSettings(joystick);

		if (joystick.joy1_y1 > 20 || joystick.joy1_y1 < -20)
      move(joystick.joy1_y1);
    else
    	move(0.0);

		encVal = nMotorEncoder[testMotor];
		motorRotations = getEncoderRotationsFloat(encVal);
		nxtDisplayTextLine(2, "%f", motorRotations);

		/*if (encVal > 1424)
		{
			nMotorEncoder[testMotor] = 0;
			//motorRotations++;
		}*/
	}
}
