#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     lightSensor,    sensorLightActive)
#pragma config(Sensor, S3,     sonarSensor,    sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     armBaseMotor,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    wristServo1,          tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    clawServoRight,       tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    clawServoLeft,        tServoStandard)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "C:\Program Files (x86)\Robomatter Inc\ROBOTC Development Environment\Sample Programs\NXT\3rd Party Sensor Drivers\drivers\lego-ultrasound.h"
#include "C:\Program Files (x86)\Robomatter Inc\ROBOTC Development Environment\Sample Programs\NXT\3rd Party Sensor Drivers\drivers\lego-light.h"

int rawLightValue;
int normalLightValue;
int distanceReading;

int openClawServos()
{
	servo[clawServoRight] = 0;
	servo[clawServoLeft] = 255;

	return 255;
}

int closeClawServos()
{
	servo[clawServoRight] = 255;
	servo[clawServoLeft] = 0;

	return 0;
}

void checkButtons()
{
	//if (nNxtButtonPressed == 1)
	//{
	//	motor[armBaseMotor] = 15;
	//}

	//else if (nNxtButtonPressed == 2)
	//{
	//	motor[armBaseMotor] = -15;
	//}

	if (nNxtButtonPressed == 1)
	{
		if (ServoValue[clawServoLeft]!= openClawServos())
			openClawServos();
		else
			closeClawServos();

		wait1Msec(250);
	}
	else
	{
		motor[armBaseMotor] = 0;
	}
}

task updateSensors()
{
	LSsetActive(lightSensor);
	while (true)
	{
		rawLightValue = LSvalRaw(lightSensor);//>10 >65
    normalLightValue = LSvalNorm(lightSensor);

    distanceReading = SensorValue[sonarSensor];
	}
}

task main()
{
	clearDebugStream();
	StartTask(updateSensors);
	while(true)
	{
		checkButtons();

    nxtDisplayTextLine(1, "Ultra Sonic:");
    nxtDisplayTextLine(2, "Dist: %4d", distanceReading);
    nxtDisplayTextLine(4, "Light Sensor:");
    nxtDisplayTextLine(5, "Raw:  %4d", rawLightValue);
    nxtDisplayTextLine(6, "Norm: %4d", normalLightValue);

    if (normalLightValue >= 50 && distanceReading < 10)
    {
    	nxtDisplayTextLine(3, "Block found!");
    	wait1Msec(1000);
    	eraseDisplay();
    }
	}
}
