#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     colorSensor,    sensorI2CCustom)
#pragma config(Sensor, S3,     sonarSensor,    sensorSONAR)
#pragma config(Sensor, S4,     eopdSensor,     sensorAnalogActive)
#pragma config(Motor,  mtr_S1_C1_1,     armBaseMotor,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    wristServoPitch,      tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    wristServoYaw,        tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    clawServoRight,       tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    clawServoLeft,        tServoStandard)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "C:\Program Files (x86)\Robomatter Inc\ROBOTC Development Environment\Sample Programs\NXT\3rd Party Sensor Drivers\drivers\lego-ultrasound.h"
#include "C:\Program Files (x86)\Robomatter Inc\ROBOTC Development Environment\Sample Programs\NXT\3rd Party Sensor Drivers\drivers\hitechnic-colour-v2.h"
#include "C:\Program Files (x86)\Robomatter Inc\ROBOTC Development Environment\Sample Programs\NXT\3rd Party Sensor Drivers\drivers\hitechnic-eopd.h"


#include "JoystickDriver.c"

//--------------------------------------
//					Global Variables
//--------------------------------------

int sonarDistanceReading;
int eopdReading = 0;
int red;
int green;
int blue;


//--------------------------------------
//					Control methods
//--------------------------------------

void armTurretRight()
{
	motor[armBaseMotor] = 15;
}

void armTurretLeft()
{
	motor[armBaseMotor] = -15;
}

int grabObject()
{
	servo[clawServoRight] = 140;
	servo[clawServoLeft] = 0;

	return 0;
}

int releaseObject()
{
	servo[clawServoRight] = 0;
	servo[clawServoLeft] = 140;

	return 140;
}

//--------------------------------------
//					Autonomous hand methods
//--------------------------------------

bool searchForBlocks()
{
	if (red > 80 && sonarDistanceReading <= 15)
	{
		return true;
	}
	else
		return false;
}

//--------------------------------------
//								Tasks
//--------------------------------------

task updateJoystickSettings()
{
  while (true)
    getJoystickSettings(joystick);
}

task updateSensors()
{
	if (!HTCS2readRGB(colorSensor, red, green, blue))
	{
    nxtDisplayTextLine(4, "ERROR!!");
    wait1Msec(2000);
    StopAllTasks();
  }

  HTEOPDsetShortRange(eopdSensor);

	while (true)
	{
		HTCS2readRGB(colorSensor, red, green, blue);
		sonarDistanceReading = SensorValue[sonarSensor];
		eopdReading = HTEOPDreadProcessed(eopdSensor);
	}
}

void checkButtons()
{
    if (joy1Btn(1))
    {

    }
    else if (joy1Btn(2))
    {

    }
    else if (joy1Btn(3))
    {

    }
    else if (joy1Btn(4))
    {

    }
    else if (joy1Btn(5))
    {

    }
    else if (joy1Btn(6))
    {

    }
    else if (joy1Btn(7))
    {

  	}
  	else if (joy1Btn(8))
    {

  	}
  	else if (joy1Btn(9))
    {

  	}
  	else if (joy1Btn(10))
    {

  	}
    else
    {
			motor[armBaseMotor] = 0;
    }
}


task main()
{
	clearDebugStream();

	StartTask(updateJoystickSettings);
	StartTask(updateSensors);

	releaseObject();
	while (true)
	{
		writeDebugStreamLine("s\te\tr\tg\tb");
		writeDebugStreamLine("%i\t%i\t%i\t%i\t%i", sonarDistanceReading, eopdReading, red, green, blue);
		wait1Msec(50);
		clearDebugStream();

		checkButtons();
		if (searchForBlocks() == true)
			grabObject();
		else
			releaseObject();

		if (joystick.joy1_TopHat != -1)
		{
      if (joystick.joy1_TopHat == 0)
      {

      }
      if (joystick.joy1_TopHat == 4)
      {

      }
      if (joystick.joy1_TopHat == 2)
      {

      }
      if (joystick.joy1_TopHat == 6)
      {

      }
    }
    else if ( abs(joystick.joy1_x2) > 20)
    {
      if (joystick.joy1_x2 > 20)
      {

      }
      else if (joystick.joy1_x2 < -20)
      {

      }
    }
    else if ( abs(joystick.joy1_y1) > 20)
    {
      if (joystick.joy1_x2 > 20)
      {

      }
      else if (joystick.joy1_x2 < -20)
      {

      }
    }
    else
    {

    }
	}
}
